version: '3.8'

services:
  app:
    image: superman961/eventsproject:1.0.0
    container_name: events_devopsj
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/eventsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    external:
      name: mysql_db # Reference the existing MySQL container

  prometheus:
    external:
      name: prometheus # Reference the existing Prometheus container

  grafana:
    external:
      name: grafana # Reference the existing Grafana container
